apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-java-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-java-jenkins
  template:
    metadata:
      labels:
        app: sample-java-jenkins
    spec:
      containers:
        - name: sample-java-jenkins
          image: sample-java-jenkins
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---

apiVersion: v1
kind: Service
metadata:
  name: sample-java-jenkins-service
  namespace: default
spec:
  selector:
    app: sample-java-jenkins
  ports:
  - port: 80
    targetPort: 8080
